-- KSU Graduation Attendance database setup
-- Run this in Supabase Dashboard > SQL Editor > New query

create table if not exists students (
  id bigint generated by default as identity primary key,
  student_id text unique not null,
  student_name text not null,
  degree text
);

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id) on delete cascade,
  attendance_date date not null default current_date,
  created_at timestamptz default now(),
  unique (student_id, attendance_date)
);

create table if not exists admins (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null
);

insert into admins (username, password)
values ('admin', '123456')
on conflict (username) do update set password = excluded.password;

alter table students enable row level security;
alter table attendance enable row level security;
alter table admins enable row level security;

drop policy if exists "students_select_anon" on students;
drop policy if exists "students_insert_anon" on students;
drop policy if exists "students_update_anon" on students;
drop policy if exists "attendance_select_anon" on attendance;
drop policy if exists "attendance_insert_anon" on attendance;
drop policy if exists "admins_select_anon" on admins;

-- Demo policies for a university project prototype.
-- For real public use, replace this with Supabase Auth / Edge Functions.
create policy "students_select_anon" on students
for select to anon using (true);

create policy "students_insert_anon" on students
for insert to anon with check (true);

create policy "students_update_anon" on students
for update to anon using (true) with check (true);

create policy "attendance_select_anon" on attendance
for select to anon using (true);

create policy "attendance_insert_anon" on attendance
for insert to anon with check (true);

create policy "admins_select_anon" on admins
for select to anon using (true);